required = [
  "k8s.io/code-generator/cmd/client-gen",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.8.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.8.2"

[[constraint]]
  name = "k8s.io/code-generator"
  # alpha.1 is missing generate-groups.sh
  #  https://github.com/kubernetes/kubernetes/issues/55536
  #  https://github.com/kubernetes/kubernetes/issues/55535
  # version = "kubernetes-1.9.0-alpha.1"
  branch = "master"
