apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scalingpolicies.scalingpolicy.kope.io
spec:
  group: scalingpolicy.kope.io
  version: v1alpha1
  names:
    kind: ScalingPolicy
    plural: scalingpolicies
  scope: Namespaced

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scaler
  namespace: kube-system
  labels:
    k8s-addon: scaler
spec:
  template:
    metadata:
      labels:
        name: scaler
        k8s-addon: scaler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            memory: 100Mi
        command:
        - /scaler
        - --v=4
        - --listen-api=:8080
        image: justinsb/scaler:latest
        name: scaler
      serviceAccountName: scaler
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler
  namespace: kube-system
  labels:
    k8s-addon: scaler

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    k8s-addon: scaler
  name: scaler
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "scalingpolicy.kope.io"
  resources:
  - scalingpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-addon: scaler
  name: scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scaler
subjects:
- kind: ServiceAccount
  name: scaler
  namespace: kube-system
