apiVersion: scalingpolicy.kope.io/v1alpha1
kind: ScalingPolicy
metadata:
  name: kube-dashboard
  namespace: kube-system
spec:
  scaleTargetRef:
    kind: Deployment
    name: kubernetes-dashboard
  containers:
  - name: kubernetes-dashboard
    resources:
      limits:
      - resource: cpu
        base: 200m
        input: cores
        slope: 250m
        segments:
        - at: 10
          roundTo: 5
        - at: 50
          roundTo: 10
  smoothing:
    scaleDownShift:
      inputs:
        cores: 20
