apiVersion: scalingpolicy.kope.io/v1alpha1
kind: ScalingPolicy
metadata:
  name: kube-dns
  namespace: kube-system
spec:
  scaleTargetRef:
    kind: Deployment
    name: kube-dns
  containers:
  - name: kubedns
    resources:
      limits:
      - resource: cpu
        base: 200m
        input: cores
        slope: 10m
        segments:
        - at: 10
          roundTo: 5
        - at: 50
          roundTo: 10
      requests:
      - resource: cpu
        base: 100m
  smoothing:
    scaleDownShift:
      inputs:
        cores: 20
